language: ruby
rvm:
- 2.4.1
install:
- ./bin/setup
script:
- bundle exec jekyll build --trace
- bundle exec htmlproofer ./_site --only-4xx --allow-hash-href --disable-external
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "develop" && "./bin/travis"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - USERNAME: mskonovalov
  - EMAIL: mskonovalov@gmail.com