language: ruby
cache: bundler
rvm:
- 2.4.1
install:
- "./bin/setup"
script:
- jekyll build --trace
- htmlproofer _site --disable-external --only-4xx --assume-extension
branches:
  only:
  - develop
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "develop" && "./bin/travis"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - USERNAME: mskonovalov
  - EMAIL: mskonovalov@gmail.com
sudo: false
dd:
  secure: JO9C5eCP6aDuVpJP+G+UML7E8hKqhSSvPzmvFAZpD89DJ/36TCYbqcnuqlYqpTAQxWpaukphpo98f3wkD087lHZ8svtuD2wVD4CMSw90lfD6qCpOfOkPVDHR7J8y4tH+KRNOz1zQ29DPZtu66yEUu/lbpNZ8569LOOTg8clcoOASn9JxaHjrXQxPL/Z0Fs/lsDyN3ydkqvs7km8a5aswhjvv7VuVQtxXILQCQAKLHGMR4+72PaMcTZh+1DU3JQ7fE9sRHWpkQBZgB1Btw9eXQIwgK1EPyFeV9bL4MNA8co7C2lSQGEZzaxhlGlwf+2XUFXGE92lp7UfgJpzEH3YDDfQSGvDJPUyP7kcngbesgYoW8eKEDNMhlwii4aezNGwfOcm49SBAG2AXcy9t9kwlKeIZn7SXaXNyZMmHmDx+7es8G6Fdb3isM/Ojxhht19Yfg9JDMD9fsg62KjdyYWGyC2/abWGaz4kAL9VRvrzI776sSLwYnesTlzI8GddSYmT+NuLf25tYK4/vUtnbqPltKyADs8O+aJwbLKSNjCBTKUrdlpaG7TusREfByyOR3g7COrp2A9PosHIUiEgYHNgc0UZPaAjoEX1a2TQ0bw+4hxyMAe+L/Icd61HPZ2JzH5iBuYm6069koJhue8OuVlpVlc6E6kgwiqFCUfqT6M9Bouk=
