language: ruby
rvm:
- 2.4.1
install:
- ./bin/setup
script:
- jekyll build --trace
- htmlproofer _site --disable-external

branches:
  only:
  - develop  

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "develop" && "./bin/travis"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - USERNAME: mskonovalov
  - EMAIL: mskonovalov@gmail.com

sudo: false # route your build to the container-based infrastructure for a faster build